services:
  scheduler:
    volumes:
      - ./etl:/usr/local/airflow/etl
      - ./data:/usr/local/airflow/data
  triggerer:
    volumes:
      - ./etl:/usr/local/airflow/etl
      - ./data:/usr/local/airflow/data
  streamlit:
    image: python:3.11-slim
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit:/app
    working_dir: /app
    command: >
      bash -c "pip install streamlit pandas sqlalchemy psycopg2-binary plotly &&
               streamlit run dashboard.py --server.port=8501 --server.address=0.0.0.0"