services:
  scheduler:
    volumes:
      - ./etl:/usr/local/airflow/etl
      - ./data:/usr/local/airflow/data
  triggerer:
    volumes:
      - ./etl:/usr/local/airflow/etl
      - ./data:/usr/local/airflow/data
  postgres:
    ports:
      - "5432:5432"
streamlit:
    image: streamlit-test
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit:/app
    working_dir: /app
    command: streamlit run dashboard.py --server.port=8501 --server.address=0.0.0.0